name: Update README with latest YouTube video

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name "aratan"
        git config user.email "victor.arbiol@gmail.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest YouTube video"
        git push origin main
